KWeb/KWeb/Controllers/AppointmentsController.cs
using KWeb.Models.Request;
using KWeb.ModelsDB;
using KWeb.Services;
using KWeb.Utils;
using KWeb.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace KWeb.Controllers
{
    public class AppointmentsController : Controller
    {
        private readonly CONSULTORIO_VIDA_SALUDEntities _context;
        private readonly EmailSystem emailSystem;

        public AppointmentsController()
        {
            emailSystem = new EmailSystem();
            _context = new CONSULTORIO_VIDA_SALUDEntities();
        }

        public ActionResult OfDoctor()
        {
            var userJson = HttpContext.Session["user"] as string;
            var user = JsonConvert.DeserializeObject<Users>(userJson);
            int DoctorId = user.Doctors.First().DoctorID;
            string Canceled = Enum.GetName(typeof(KWeb.Utils.AppointmentsStatusEnum), KWeb.Utils.AppointmentsStatusEnum.Canceled);

            var appointments = _context.Appointments
                .Where(a => DbFunctions.TruncateTime(a.Date) == DateTime.Today && a.DoctorID == DoctorId && a.Status != Canceled)
                .ToList();

            var tomorrow = DateTime.Today.AddDays(1);
            var appointmentsScheduled = _context.Appointments
                .Where(a => DbFunctions.TruncateTime(a.Date) >= tomorrow && a.DoctorID == DoctorId)
                .ToList();

            var viewModel = new AppointmentsOfDoctorViewModel
            {
                AppointmentsScheduled = appointmentsScheduled,
                AppointmentsToday = appointments
            };

            return View(viewModel);
        }
        public async Task<ActionResult> OfPatient()
        {
            var userJson = HttpContext.Session["user"] as string;
            var user = JsonConvert.DeserializeObject<Users>(userJson);
            int PatientId = user.Patients.First().PatientID;

            var appointments = await _context.Appointments.Where(a => a.PatientID == PatientId).ToListAsync();
            var doctors = await _context.Doctors.Where(d => d.Users.IsActive).ToListAsync();

            var viewModel = new AppointmentsOfPatientViewModel
            {     
                Doctors = doctors,
                AppointmentRequest = new AppointmentRequest()
                {
                    Date = DateTime.Now.AddDays(1)
                }
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Register(AppointmentsOfPatientViewModel vm)
        {
            AppointmentRequest model = vm.AppointmentRequest;

            var userJson = HttpContext.Session["user"] as string;
            var user = JsonConvert.DeserializeObject<Users>(userJson);

            model.PatientID = user.Patients.First().PatientID; 

            if (ModelState.IsValid)
            {
                var newAppointment = new Appointments
                {
                    PatientID = model.PatientID,
                    DoctorID = model.DoctorID,
                    Date = model.Date,
                    BlockID = model.BlockID,
                    Status = Enum.GetName(typeof(AppointmentsStatusEnum), AppointmentsStatusEnum.Scheduled),
                    Notes = model.Notes
                };

                _context.Appointments.Add(newAppointment);
                await _context.SaveChangesAsync();

                var appointmentRecently = _context.Appointments
                    .Include(a => a.Patients)
                     .Include(p => p.Patients.Users) // Incluir la relación con Users dentro de Patient
                    .Include(a => a.Doctors)
                    .Include(a => a.Blocks)
                    .FirstOrDefault(a => a.AppointmentID == newAppointment.AppointmentID);

                TempData["SuccessMessage"] = "La cita se agendo correctamente.";

                emailSystem.ScheduledPatientAppointment(appointmentRecently.Patients.Users.Email, appointmentRecently);
                emailSystem.ScheduledDoctorAppointment(appointmentRecently.Doctors.Users.Email, appointmentRecently);

                return RedirectToAction("OfPatient");
            }

            TempData["ErrorMessage"] = "No se pudo agendar la cita.";

            return RedirectToAction("OfPatient");
            
        }

        [HttpPost]
        public ActionResult AttendAppointment(int appointmentId, string notes, int blockId, int doctorId)
        {
            var appointment = _context.Appointments.FirstOrDefault(a => a.AppointmentID == appointmentId);

            var medicalHistory = new MedicalHistory
            {
                AppointmentId = appointmentId,
                ConsultationDate = DateTime.Now.Date,
                Notes = notes
            };
            _context.MedicalHistory.Add(medicalHistory);

            appointment.Status = Enum.GetName(typeof(KWeb.Utils.AppointmentsStatusEnum), KWeb.Utils.AppointmentsStatusEnum.Completed);

            _context.SaveChanges();

            return RedirectToAction("OfDoctor");
        }

        [HttpPost]
        public ActionResult CancelAppointment(int appointmentId)
        {
            var appointment = _context.Appointments
                   .Include(a => a.Patients)
                    .Include(p => p.Patients.Users)
                   .Include(a => a.Doctors)
                   .Include(a => a.Blocks)
                   .FirstOrDefault(a => a.AppointmentID == appointmentId);

            appointment.Status = Enum.GetName(typeof(KWeb.Utils.AppointmentsStatusEnum), KWeb.Utils.AppointmentsStatusEnum.Canceled);

            _context.SaveChanges();

            emailSystem.CanceledPatientAppointment(appointment.Patients.Users.Email, appointment);

            return RedirectToAction("OfDoctor");
        }

    }
}

KWeb/KWeb/Views/Appointments/Partials/_AttendAppointmentModal.cshtml
@model KWeb.ModelsDB.Appointments

<div class="modal fade" id="attendAppointmentModal_@Model.AppointmentID" tabindex="-1" aria-labelledby="attendAppointmentModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="attendAppointmentModalLabel">Atender Cita</h5>
            </div>
            <div class="modal-body">
                <form action="@Url.Action("AttendAppointment", "Appointments")" method="post">
                    <div class="mb-3">
                        <label for="appointmentNotes" class="form-label">Diagnostico</label>
                        <textarea class="form-control" id="appointmentNotes" name="notes" rows="3" required></textarea>
                    </div>
                    <input type="hidden" name="appointmentId" value="@Model.AppointmentID">
                    <input type="hidden" name="blockId" value="@Model.BlockID">
                    <input type="hidden" name="doctorId" value="@Model.DoctorID">

                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Guardar Diagnostico</button>
                </form>
            </div>
          
        </div>
    </div>
</div>

KWeb/KWeb/Views/Appointments/Partials/_CancelAppointmentModal.cshtml
@model KWeb.ModelsDB.Appointments

<div class="modal fade" id="cancelAppointmentModal_@Model.AppointmentID" tabindex="-1" aria-labelledby="cancelAppointmentModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cancelAppointmentModalLabel">Cancelar Cita</h5>
            </div>
            <div class="modal-body">
                <div class="alert">
                    <p class="h6">Los siguientes usuarios afectados seran notificados:</p>
                    
                    <p>@Model.Patients.Users.FirstName @Model.Patients.Users.LastName</p>

                </div>
                <form action="@Url.Action("CancelAppointment", "Appointments")" method="post">
                  
                    <input type="hidden" name="appointmentId" value="@Model.AppointmentID">           

                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-danger">Cancelar cita</button>
                </form>
            </div>

        </div>
    </div>
</div>